FROM node:18-alpine AS builder
WORKDIR /app
COPY ruoyi-ui/package*.json ./
RUN npm install --legacy-peer-deps
COPY ruoyi-ui/ .
RUN NODE_OPTIONS=--openssl-legacy-provider npm run build:prod

FROM nginx:1.25-alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
